version: '2.0'

services:

  moradb:
    env_file:
      - ./.env
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 7001:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSUSER}
      MYSQL_ROOT_PASSWORD: ${PASSROOT}
      MYSQL_INITDB_SKIP_TZINFO: ${MYSQL_INITDB_SKIP_TZINFO}
    restart: always 
    volumes:
      - ./docker/mysql:/var/lib/mysql

  moraapi:
    build: ./docker/moraapi
    ports:
      - 7002:8000
    #restart: always 
    volumes:
      - ./api:/home/api
    links:
      - moradb


  morasystem:
    build: ./docker/morasystem
    ports:
      - 7000:80
    #restart: always 
    volumes:
      - ./public:/home/morasystem
    command: python ./violeta/manage.py runserver 0:80
    links:
      - moradb
