version: '3'

services:

  web:
    build: ./docker/cobra_system
    env_file:
      - ./.env
    volumes:
      - ./public/sistema_cobranza:/home/sistema_cobranza
    ports:
      - ${SYSTEM_PORT}:8000
    command: sh -c "python ./manage.py runserver 0:8000"
    
    depends_on:
      - db
    networks:
      - red-interna
    

  db:
    env_file:
      - ./.env
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
      PGTZ: ${TZ}
    restart: always 
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - red-interna


networks:
    red-interna:
        driver: bridge

volumes:
  db-data:
