version: '2.0'

services:

  moradb:
    env_file:
      - ./.env
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 7001:3306
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSUSER}
      MYSQL_ROOT_PASSWORD: ${PASSROOT}
    restart: always 
    volumes:
      - ./docker/mysql:/var/lib/mysql

  morasystem:
    build: ./docker/php
    ports:
      - 7000:5673
    volumes:
      - ./public:/var/www/html
    command: composer create-project --prefer-dist cakephp/app:4.* violeta    
    command: chmod -R 777 violeta
    command: cd violeta
    command: composer require "cakephp/authentication:^2.0"
    command: violeta/bin/cake server -H 0.0.0.0 -p 5673
    links:
      - moradb

  #moraapi:
  #  build: ./docker/python
  #  ports:
  #    - 7002:8000
  #  #restart: always 
  #  volumes:
  #    - ./api:/home/api
  #  links:
  #    - moradb



