version: '3'

services:

  cobra_system:
    build: ./docker/cobra_system
    env_file:
      - ./.env
    ports:
      - ${SYSTEM_PORT}:80
    volumes:
      - ./public:/home/cobra_system
    command: sh -c "python /home/cobra_system/sistema_cobranza/manage.py runserver 0:80"
    depends_on:
      - cobra_db
    networks:
      - cobra-red
    

  cobra_db:
    env_file:
      - ./.env
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
      PGTZ: ${TZ}
    restart: always 
    volumes:
      - cobra-data:/var/lib/postgresql/data
    networks:
      - cobra-red


networks:
    cobra-red:
        driver: bridge

volumes:
  cobra-data:
