version: '3'

services:

  cobra_db:
    env_file:
      - ./.env
    image: postgres:${POSTGRES_VERSION}
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
      PGTZ: ${TZ}
    restart: always 
    volumes:
      - cobra-data:/var/lib/postgresql/data


  cobra_system:
    build: ./docker/cobra_system
    env_file:
      - ./.env
    ports:
      - ${SYSTEM_PORT}:80
    volumes:
      - ./public:/home/cobra_system
    command: sh -c "python /home/cobra_system/sistema_cobranza/manage.py runserver 0:80"
    links:
      - cobra_db
    depends_on:
      - cobra_db

#  moraapi:
#    build: ./docker/moraapi
#    ports:
#      - 7002:8000
#    #restart: always 
#    volumes:
#      - ./api:/home/api
#    links:
#      - moradb

volumes:
  cobra-data:
