version: '3'

services:

  web:
    build: ./docker/cobra_system
    env_file:
      - ./.env
    restart: always 
    volumes:
      - ./public/sistema_cobranza:/home/sistema_cobranza
    command: gunicorn --bind 0.0.0.0:${SYSTEM_PORT} sistema_cobranza.wsgi
    depends_on:
      - db
    networks:
      - red-interna
    

  db:
    env_file:
      - ./.env
    image: postgres:${POSTGRES_VERSION}
    expose:
      - ${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
      PGTZ: ${TZ}
    restart: always 
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - red-interna


  server:
    build: ./docker/nginx
    ports:
      - 80:80
    restart: always 
    volumes:
      - ./public/sistema_cobranza/staticfiles:/home/sistema_cobranza/staticfiles
    depends_on:
      - web
    networks:
      - red-interna


networks:
    red-interna:
        driver: bridge

volumes:
  db-data:
