FROM python:3.9-slim

RUN apt-get update && \
	apt-get install libpq-dev gcc -y

ENV TZ = America/Argentina/Mendoza

WORKDIR /home/cobra_system

EXPOSE 80

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt