# Generated by Django 3.1.7 on 2021-04-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
