# Generated by Django 3.2.13 on 2022-06-18 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0003_auto_20210404_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='ubicacion',
            new_name='detalle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente'),
        ),
    ]
