# Generated by Django 3.2.13 on 2022-06-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0005_auto_20220618_0340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link_cliente',
        ),
    ]
