# Generated by Django 3.2.13 on 2022-06-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0006_delete_link_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento_telefono',
            name='evento_respuesta',
        ),
        migrations.RemoveField(
            model_name='evento_telefono',
            name='evento_tipo',
        ),
        migrations.RemoveField(
            model_name='evento_telefono',
            name='fecha_creado',
        ),
        migrations.RemoveField(
            model_name='evento_telefono',
            name='fecha_modificado',
        ),
        migrations.RemoveField(
            model_name='evento_telefono',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.empresa'),
        ),
        migrations.AlterField(
            model_name='evento_pendiente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente'),
        ),
        migrations.AlterField(
            model_name='evento_telefono',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.telefono'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.empresa'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.estado'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='mora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.mora'),
        ),
        migrations.AlterField(
            model_name='lista_cliente',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente'),
        ),
        migrations.AlterField(
            model_name='lista_cliente',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.estado'),
        ),
        migrations.AlterField(
            model_name='lista_cliente',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.lista'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.estado'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono_tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.telefono_tipo'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificado', models.DateTimeField(auto_now=True, null=True)),
                ('evento_respuesta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.evento_respuesta')),
                ('evento_tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.evento_tipo')),
            ],
        ),
        migrations.AddField(
            model_name='evento_telefono',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.evento'),
        ),
    ]
