# Generated by Django 3.2.13 on 2022-06-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0007_auto_20220622_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente'),
        ),
    ]
