# Generated by Django 3.2.13 on 2022-06-22 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0008_evento_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='telefono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.telefono'),
        ),
        migrations.DeleteModel(
            name='Evento_telefono',
        ),
    ]
