# Generated by Django 3.2.13 on 2022-06-24 11:04

import cobranza_mora.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranza_mora', '0009_auto_20220622_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=models.SET(cobranza_mora.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
