# Generated by Django 3.2.13 on 2022-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0010_evento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='fecha_modificado',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='lista',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
