# Generated by Django 3.2.13 on 2022-06-26 12:06

import cobranza_mora.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cobranza_mora', '0011_auto_20220626_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=models.SET(cobranza_mora.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lista_cliente',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=models.SET(cobranza_mora.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
