# Generated by Django 3.2.13 on 2022-07-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza_mora', '0012_auto_20220626_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.FloatField()),
                ('medio', models.CharField(max_length=140)),
                ('fecha_pago', models.DateTimeField(null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.cliente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cobranza_mora.estado')),
            ],
        ),
    ]
