FROM python:3.8-alpine

RUN mkdir -p /home/api

WORKDIR /home/api

EXPOSE 8000

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app","--reload", "--host", "0.0.0.0", "--port", "8000"]