FROM python:3.8-alpine

RUN mkdir -p /home/morasistem

WORKDIR /home/morasystem

EXPOSE 80

COPY ./requirements.txt .

RUN apk update \
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add --no-cache mariadb-dev

RUN pip install --no-cache-dir -r requirements.txt

RUN apk del build-deps