FROM python:3.9-slim

RUN apt-get update && \
	apt-get install python3-dev default-libmysqlclient-dev gcc -y

ENV TZ = America/Argentina/Mendoza

RUN mkdir -p /home/mora_sistem

WORKDIR /home/mora_system

EXPOSE 80

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt